### ISSUE TITLE
3-letter codes

### ISSUE THREAD

**Issue by hitz** [EBISPOT/hancestro#27]
It would be great if HANCESTRO could cross refence the commonly used 3-letter codes, e..,g from 1000 genomes and other projects.

As it stands it's an extremely manual process to hancestro-ize data that uses 3 letter codes.

**Comment by daniwelter** [comment]
@hitz thanks for raising this issue. We just started a new development cycle last week and this is indeed on our development road map. We are planning on incorporating the 1000 Genomes and HapMap collections (from https://www.coriell.org/0/Sections/Collections/NHGRI/1000genome.aspx?PgId=664&coll=HG) where appropriate. If there are additional ones you require, or if you have existing mappings you'd like us to take into consideration, please feel free to share them here.

**Comment by hitz** [comment]
This is maybe the most useful list I found: https://useast.ensembl.org/Help/Faq?id=532. But I am sort of shocked (well not really) that there isn't an official nomenclature group.  Actually I will ping GA4GH on slack

**Comment by daniwelter** [comment]
Completed in release #60
