### ISSUE TITLE
Add parent classes for ethnicity and ancestry terms

### ISSUE THREAD

**Issue by brianraymor** [EBISPOT/hancestro#46]
The CELLxGENE Discover schema has limited metadata but strict requirements and enforcement by our validator. Each version of the schema also defines (pins) the specific release for each ontology that we use. This allows us to write extremely specific requirements related to each ontology.

From a validation perspective, it's simpler to block terms based on the ontology hierarchy (must be a child of a specific term for example) or properties (like deprecated) **It would be extremely helpful if there was a simple way to determine the set of HANCESTRO terms appropriate for either ethnicity or ancestry.**

Otherwise, we're forced to manually review the ontology during schema updates and cherry pick exceptions term by term. And the more complex our schema requirements, the more overhead there is for the curators who must observe the requirements.  In addition, it appears that many terms in HANCESTRO are missing descriptions (IAO_0000115)?

Please see the current schema requirements for [self-reported ethnicity](https://github.com/chanzuckerberg/single-cell-curation/blob/main/schema/4.0.0/schema.md#self_reported_ethnicity_ontology_term_id) which illustrate this complexity.

**Comment by daniwelter** [comment]
I believe this was addressed through the last 2 releases. Please reopen if more work is needed.
